version: "2.2"

networks: 
  moodle-net:

services:
 moodle: 
  image: moodle
  container_name: moodle
  ports:
    - 80:80
  networks:
    - moodle-net

 db:
  image: mysql:8.0
  container_name: moodle_db
  command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
  restart: always
  environment:
    MYSQL_DATABASE: moodle
    MYSQL_USER: admin
    MYSQL_PASSWORD: adminpw
    MYSQL_ROOT_PASSWORD: adminpw
  ports:
    - 3306:3306
  networks: 
    - moodle-net
 
